# Generated by Django 4.1 on 2023-05-19 15:36
# python manage.py makemigrations --empty -n fill_test iqtest
import json

from django.conf import settings
from django.db import migrations


def forwards_func(apps, schema_editor):
    Test = apps.get_model('iqtest', 'Test')
    tests = json.loads(
        (settings.BASE_DIR / 'iqtest' / 'migrations' / 'test_data' / 'test.json').read_text(
            encoding="utf-8"))
    objs = []
    for test in tests:
        objs.append(Test(id=test.get('id'), question=test.get('question'), correct=test.get('correct'),
                              answer1=test.get('answer1'), answer2=test.get('answer2'),
                              answer3=test.get('answer3'), answer4=test.get('answer4'),
                              answer5=test.get('answer5')))

    Test.objects.bulk_create(objs)


def reverse_func(apps, schema_editor):
    Test = apps.get_model('iqtest', 'Test')
    Test.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('iqtest', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
